// Premade template presets that vendors can pick with one click
// Each template provides a full "design recipe" — colors, fonts, layouts, and sections.

// ─── Shared font family map ──────────────────────────────────
export const FONT_MAP: Record<string, string> = {
  inter: "'Inter', sans-serif",
  poppins: "'Poppins', sans-serif",
  roboto: "'Roboto', sans-serif",
  playfair: "'Playfair Display', serif",
  montserrat: "'Montserrat', sans-serif",
  outfit: "'Outfit', sans-serif",
  dmSans: "'DM Sans', sans-serif",
  spaceGrotesk: "'Space Grotesk', sans-serif",
};
export type TemplateSection = {
  id: string;
  enabled: boolean;
  order: number;
};

export type TemplateSectionContent = {
  [sectionId: string]: Record<string, any>;
};

export type Template = {
  id: string;
  name: string;
  description: string;
  emoji: string;
  category: string;
  tags: string[];
  theme: {
    primary_color: string;
    secondary_color: string;
    background_color: string;
    text_color: string;
    accent_color: string;
    surface_color: string;
    heading_color: string;
    border_color: string;
    font_family: string;
    heading_font: string;
    font_size: "small" | "medium" | "large";
    layout_style: "grid" | "list" | "masonry";
    card_style: "modern" | "classic" | "minimal" | "bold";
    border_radius: "sharp" | "rounded" | "pill";
    card_shadow: "none" | "soft" | "elevated" | "hard";
    button_style: "solid" | "outline" | "soft" | "glass";
    button_radius: "sharp" | "rounded" | "pill";
    animation_style: "none" | "fade" | "slide" | "zoom" | "bounce";
    spacing: "compact" | "comfortable" | "spacious";
    header_style: "sticky" | "static" | "transparent";
    image_aspect_ratio: "square" | "portrait" | "landscape";
    primary_gradient: string | null;
    glass_effect: boolean;
    layout_width: "standard" | "wide" | "full";
    show_mobile_checkout_bar: boolean;
    logo_position?: "left" | "center" | "right";
    logo_frame?: "plain" | "none" | "profile" | "rounded" | "minimal";
    icon_library?: "heroicons" | "lucide";
    icon_fill?: "solid" | "outline";
    icon_weight?: "light" | "regular" | "bold";
    cart_icon?: "shopping-bag" | "shopping-cart" | "basket" | "tote";
    user_icon?: "user" | "face" | "smile";
    share_icon?:
      | "dots"
      | "paper-plane"
      | "arrow-curve"
      | "arrow-square"
      | "nodes";
    add_icon?: "plus" | "bag" | "cart" | "arrow";
  };
  sections: TemplateSection[];
  sectionContent: TemplateSectionContent;
};

// ─── Available section types ─────────────────────────────────
export const SECTION_TYPES = [
  {
    id: "hero-banner",
    label: "Hero Banner",
    icon: "🖼️",
    description: "Full-width banner with store name and tagline",
    removable: true,
  },
  {
    id: "announcement-bar",
    label: "Announcement Bar",
    icon: "📢",
    description: "Scrolling promo text marquee",
    removable: true,
  },
  {
    id: "featured-products",
    label: "Featured Products",
    icon: "⭐",
    description: "Hand-picked product highlights",
    removable: true,
  },
  {
    id: "product-grid",
    label: "Product Grid",
    icon: "📦",
    description: "Main product listing",
    removable: false,
  },
  {
    id: "trust-badges",
    label: "Trust Badges",
    icon: "🛡️",
    description: "Secure checkout, fast delivery badges",
    removable: true,
  },
  {
    id: "image-gallery",
    label: "Image Gallery",
    icon: "🎨",
    description: "Photo gallery with lightbox",
    removable: true,
  },
  {
    id: "faqs",
    label: "FAQs",
    icon: "❓",
    description: "Frequently asked questions",
    removable: true,
  },
  {
    id: "testimonials",
    label: "Testimonials",
    icon: "💬",
    description: "Customer quotes and reviews",
    removable: true,
  },
  {
    id: "about-section",
    label: "About Us",
    icon: "🏪",
    description: "Your store's story",
    removable: true,
  },
  {
    id: "contact-cta",
    label: "Contact / CTA",
    icon: "📲",
    description: '"Order on WhatsApp" call-to-action',
    removable: true,
  },
  {
    id: "newsletter",
    label: "Newsletter",
    icon: "✉️",
    description: "Email signup for updates",
    removable: true,
  },
  {
    id: "video-promo",
    label: "Video Promo",
    icon: "🎥",
    description: "Featured video or background",
    removable: true,
  },
  {
    id: "logo-cloud",
    label: "Logo Cloud",
    icon: "🏢",
    description: "Brand partners or trusted by logos",
    removable: true,
  },
  {
    id: "rich-text",
    label: "Rich Text",
    icon: "📝",
    description: "Flexible text block with styling",
    removable: true,
  },
  {
    id: "split-feature",
    label: "Split Feature",
    icon: "◨",
    description: "Side-by-side image and text block",
    removable: true,
  },
  {
    id: "category-grid",
    label: "Category Grid",
    icon: "📂",
    description: "Quick links to categories",
    removable: true,
  },
] as const;

// ─── Template categories ─────────────────────────────────────
export const TEMPLATE_CATEGORIES = [
  { id: "all", label: "All Themes" },
  { id: "fashion", label: "Fashion" },
  { id: "food", label: "Food & Drink" },
  { id: "tech", label: "Tech" },
  { id: "beauty", label: "Beauty" },
  { id: "artisan", label: "Artisan" },
  { id: "premium", label: "Premium" },
  { id: "sports", label: "Sports & Fitness" },
] as const;

// ─── Default section set ─────────────────────────────────────
const DEFAULT_SECTIONS: TemplateSection[] = [
  { id: "hero-banner", enabled: true, order: 0 },
  { id: "announcement-bar", enabled: false, order: 1 },
  { id: "featured-products", enabled: false, order: 2 },
  { id: "product-grid", enabled: true, order: 3 },
  { id: "trust-badges", enabled: true, order: 4 },
  { id: "image-gallery", enabled: false, order: 5 },
  { id: "faqs", enabled: false, order: 6 },
  { id: "testimonials", enabled: false, order: 7 },
  { id: "about-section", enabled: false, order: 8 },
  { id: "contact-cta", enabled: true, order: 9 },
];

const DEFAULT_SECTION_CONTENT: TemplateSectionContent = {
  "hero-banner": {
    title: "Welcome to our store",
    subtitle: "Browse our collection and order directly via WhatsApp.",
    cta_text: "Shop Now",
    cta_link: "#item-list",
    text_align: "left",
  },
  "announcement-bar": {
    text: "Free delivery on orders over ₦5,000!",
    bg_color: "#10b981",
    text_color: "#ffffff",
  },
  "featured-products": {
    title: "Featured",
    product_ids: [],
  },
  "trust-badges": {
    badges: [
      { icon: "shield", label: "Secure Checkout" },
      { icon: "truck", label: "Fast Delivery" },
      { icon: "return", label: "Easy Returns" },
      { icon: "chat", label: "WhatsApp Support" },
    ],
  },
  "image-gallery": {
    title: "Gallery",
    images: [
      {
        url: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600&h=600&fit=crop",
        caption: "Our Store",
      },
      {
        url: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400&h=400&fit=crop",
        caption: "Shopping Experience",
      },
      {
        url: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=400&h=400&fit=crop",
        caption: "New Arrivals",
      },
      {
        url: "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=400&h=400&fit=crop",
        caption: "Fashion Forward",
      },
      {
        url: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=600&h=600&fit=crop",
        caption: "Premium Collection",
      },
    ],
  },
  faqs: {
    title: "Frequently Asked Questions",
    items: [
      {
        question: "Do you offer delivery?",
        answer: "Yes! We deliver across the country. Delivery fees may vary.",
      },
      {
        question: "What is your return policy?",
        answer:
          "We offer a 7-day return policy for unused products in their original packaging.",
      },
    ],
  },
  testimonials: {
    quotes: [
      {
        name: "Happy Customer",
        text: "Great products and fast delivery!",
        rating: 5,
      },
    ],
  },
  "about-section": {
    title: "About Us",
    text: "We are passionate about providing the best products to our customers.",
  },
  "contact-cta": {
    title: "Have questions?",
    subtitle: "Reach us directly on WhatsApp for faster response.",
    button_text: "Chat on WhatsApp",
  },
  newsletter: {
    title: "Join our mailing list",
    subtitle: "Get the latest updates and exclusive offers.",
    placeholder: "your@email.com",
    button_text: "Subscribe",
  },
  "video-promo": {
    title: "Our Story",
    video_url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
    autoplay: false,
    aspect_ratio: "16/9",
  },
  "logo-cloud": {
    title: "Trusted By",
    logos: [
      {
        url: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
        name: "Amazon",
      },
      {
        url: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Slack_Technologies_Logo.svg",
        name: "Slack",
      },
    ],
  },
  "rich-text": {
    title: "Quality you can trust",
    text: "We pride ourselves on sourcing the best materials and working with local artisans.",
    align: "center",
    size: "medium",
  },
  "category-grid": {
    title: "Shop by Category",
    categories: [
      {
        id: "1",
        name: "New Arrivals",
        image_url:
          "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=300&h=300&fit=crop",
        link: "#item-list",
      },
      {
        id: "2",
        name: "Best Sellers",
        image_url:
          "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=300&h=300&fit=crop",
        link: "#item-list",
      },
    ],
  },
};

// ─── Template Library ────────────────────────────────────────
export const TEMPLATES: Template[] = [
  // ── 1. Fresh Market (preserved ID) ─────────────────────────
  {
    id: "fresh-market",
    name: "Fresh Market",
    description:
      "Vibrant and lively — perfect for food, groceries & produce vendors.",
    emoji: "🥬",
    category: "food",
    tags: ["food", "grocery", "colourful"],
    theme: {
      primary_color: "#16a34a",
      secondary_color: "#15803d",
      background_color: "#f0fdf4",
      text_color: "#14532d",
      accent_color: "#eab308",
      surface_color: "#ffffff",
      heading_color: "#052e16",
      border_color: "#bbf7d0",
      font_family: "poppins",
      heading_font: "poppins",
      font_size: "medium",
      layout_style: "grid",
      card_style: "modern",
      border_radius: "rounded",
      card_shadow: "soft",
      button_style: "solid",
      button_radius: "pill",
      animation_style: "bounce",
      spacing: "comfortable",
      header_style: "sticky",
      image_aspect_ratio: "square",
      primary_gradient: "linear-gradient(135deg, #f59e0b, #d97706)",
      glass_effect: false,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "left",
      logo_frame: "profile",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "announcement-bar", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
      { id: "trust-badges", enabled: true, order: 3 },
      { id: "contact-cta", enabled: true, order: 4 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Fresh picks, delivered fast",
        subtitle: "Farm-fresh groceries and produce at your fingertips.",
        cta_text: "Browse Products",
        cta_link: "#item-list",
        text_align: "left",
      },
      "announcement-bar": {
        text: "New stock just arrived — order before it's gone!",
        bg_color: "#16a34a",
        text_color: "#ffffff",
      },
    },
  },

  // ── Sports & Fitness: Pro Athlete (NEW) ───────────────────
  {
    id: "pro-athlete",
    name: "Pro Athlete",
    description:
      "High-energy dark theme with neon accents for athletic brands.",
    emoji: "⚡",
    category: "sports",
    tags: ["sports", "athletic", "dark"],
    theme: {
      primary_color: "#00d4ff",
      secondary_color: "#0a0a0f",
      background_color: "#0a0a0f",
      text_color: "#e6f7ff",
      accent_color: "#ff2d78",
      surface_color: "#0f1113",
      heading_color: "#ffffff",
      border_color: "#111217",
      font_family: "outfit",
      heading_font: "spaceGrotesk",
      font_size: "medium",
      layout_style: "grid",
      card_style: "bold",
      border_radius: "sharp",
      card_shadow: "elevated",
      button_style: "solid",
      button_radius: "rounded",
      animation_style: "zoom",
      spacing: "compact",
      header_style: "sticky",
      image_aspect_ratio: "landscape",
      primary_gradient: "linear-gradient(90deg, #00d4ff, #00a3e0)",
      glass_effect: false,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "left",
      logo_frame: "minimal",
    },
    sections: DEFAULT_SECTIONS,
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Train like a Pro",
        subtitle: "Top-tier athletic gear for peak performance.",
        cta_text: "Shop Now",
        cta_link: "#item-list",
        text_align: "left",
      },
    },
  },

  // ── Sports & Fitness: Urban Runner (NEW) ────────────────
  {
    id: "urban-runner",
    name: "Urban Runner",
    description: "Clean, bright running-focused theme with vivid lime accents.",
    emoji: "🏃",
    category: "sports",
    tags: ["sports", "running", "clean"],
    theme: {
      primary_color: "#84cc16",
      secondary_color: "#f9fafb",
      background_color: "#f9fafb",
      text_color: "#1a2e05",
      accent_color: "#84cc16",
      surface_color: "#ffffff",
      heading_color: "#0b2a05",
      border_color: "#e6f4d6",
      font_family: "montserrat",
      heading_font: "montserrat",
      font_size: "medium",
      layout_style: "grid",
      card_style: "modern",
      border_radius: "rounded",
      card_shadow: "soft",
      button_style: "solid",
      button_radius: "pill",
      animation_style: "slide",
      spacing: "comfortable",
      header_style: "sticky",
      image_aspect_ratio: "portrait",
      primary_gradient: null,
      glass_effect: false,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "left",
      logo_frame: "rounded",
    },
    sections: DEFAULT_SECTIONS,
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Run the City",
        subtitle: "Lightweight gear built for speed and comfort.",
        cta_text: "Explore",
        cta_link: "#item-list",
        text_align: "center",
      },
    },
  },

  // ── Sports & Fitness: Gym & Iron (NEW) ────────────────
  {
    id: "gym-iron",
    name: "Gym & Iron",
    description: "Raw, industrial gym aesthetic for strength and power brands.",
    emoji: "🏋️",
    category: "sports",
    tags: ["sports", "gym", "strength"],
    theme: {
      primary_color: "#f97316",
      secondary_color: "#111111",
      background_color: "#111111",
      text_color: "#f5f5f5",
      accent_color: "#f97316",
      surface_color: "#0f0f0f",
      heading_color: "#ffffff",
      border_color: "#222222",
      font_family: "roboto",
      heading_font: "montserrat",
      font_size: "medium",
      layout_style: "grid",
      card_style: "bold",
      border_radius: "sharp",
      card_shadow: "hard",
      button_style: "solid",
      button_radius: "rounded",
      animation_style: "bounce",
      spacing: "compact",
      header_style: "sticky",
      image_aspect_ratio: "landscape",
      primary_gradient: null,
      glass_effect: false,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "left",
      logo_frame: "profile",
    },
    sections: DEFAULT_SECTIONS,
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Built for Strength",
        subtitle: "Durable equipment and apparel for heavy lifters.",
        cta_text: "Shop Strength",
        cta_link: "#item-list",
        text_align: "left",
      },
    },
  },
  // ── 2. Luxe Boutique (preserved ID) ────────────────────────
  {
    id: "luxe-boutique",
    name: "Luxe Boutique",
    description:
      "Sleek and elegant — ideal for fashion, jewellery & luxury lifestyle.",
    emoji: "✨",
    category: "fashion",
    tags: ["fashion", "luxury", "minimal"],
    theme: {
      primary_color: "#18181b",
      secondary_color: "#27272a",
      background_color: "#fafafa",
      text_color: "#18181b",
      accent_color: "#c59b3f",
      surface_color: "#ffffff",
      heading_color: "#09090b",
      border_color: "#e4e4e7",
      font_family: "inter",
      heading_font: "playfair",
      font_size: "medium",
      layout_style: "masonry",
      card_style: "minimal",
      border_radius: "sharp",
      card_shadow: "none",
      button_style: "outline",
      button_radius: "sharp",
      animation_style: "fade",
      spacing: "comfortable",
      header_style: "transparent",
      image_aspect_ratio: "portrait",
      primary_gradient: null,
      glass_effect: true,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "center",
      logo_frame: "minimal",
      icon_library: "lucide",
      icon_fill: "outline",
      icon_weight: "light",
      cart_icon: "shopping-bag",
      user_icon: "user",
      share_icon: "paper-plane",
      add_icon: "arrow",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "product-grid", enabled: true, order: 1 },
      { id: "image-gallery", enabled: true, order: 2 },
      { id: "trust-badges", enabled: true, order: 3 },
      { id: "testimonials", enabled: true, order: 4 },
      { id: "contact-cta", enabled: true, order: 5 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "featured-products": {
        title: "Featured",
        product_ids: [],
      },
      "hero-banner": {
        title: "Curated for you",
        subtitle: "Discover exclusive pieces handpicked with care.",
        cta_text: "Explore Collection",
        cta_link: "#item-list",
        text_align: "center",
      },
      "trust-badges": {
        badges: [
          { icon: "star", label: "Authentic Products" },
          { icon: "gift", label: "Premium Packaging" },
          { icon: "truck", label: "Express Delivery" },
          { icon: "chat", label: "24/7 Support" },
        ],
      },
      testimonials: {
        quotes: [
          {
            name: "Chioma A.",
            text: "Absolutely stunning quality. Will buy again!",
            rating: 5,
          },
          {
            name: "Adaeze",
            text: "Fast delivery and beautiful packaging.",
            rating: 5,
          },
        ],
      },
    },
  },

  // ── 3. Tech Store (preserved ID) ───────────────────────────
  {
    id: "tech-store",
    name: "Tech Store",
    description: "Clean, bold & modern — built for electronics & gadgets.",
    emoji: "📱",
    category: "tech",
    tags: ["electronics", "gadgets", "modern"],
    theme: {
      primary_color: "#2563eb",
      secondary_color: "#1d4ed8",
      background_color: "#f8fafc",
      text_color: "#1e293b",
      accent_color: "#06b6d4",
      surface_color: "#ffffff",
      heading_color: "#0f172a",
      border_color: "#e2e8f0",
      font_family: "inter",
      heading_font: "spaceGrotesk",
      font_size: "medium",
      layout_style: "grid",
      card_style: "modern",
      border_radius: "rounded",
      card_shadow: "elevated",
      button_style: "solid",
      button_radius: "rounded",
      animation_style: "zoom",
      spacing: "comfortable",
      header_style: "sticky",
      image_aspect_ratio: "square",
      primary_gradient: "linear-gradient(135deg, #10b981, #059669)",
      glass_effect: true,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "left",
      logo_frame: "rounded",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "featured-products", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
      { id: "trust-badges", enabled: true, order: 3 },
      { id: "contact-cta", enabled: true, order: 4 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Power up your tech",
        subtitle: "Genuine gadgets, accessories, and electronics.",
        cta_text: "Shop Now",
        cta_link: "#item-list",
        text_align: "left",
      },
      "featured-products": {
        title: "Hot Deals",
        product_ids: [],
      },
    },
  },

  // ── 4. Beauty & Glow (preserved ID) ────────────────────────
  {
    id: "beauty-glow",
    name: "Beauty & Glow",
    description:
      "Soft pastels and feminine elegance — for skincare & beauty brands.",
    emoji: "🌸",
    category: "beauty",
    tags: ["beauty", "skincare", "feminine"],
    theme: {
      primary_color: "#db2777",
      secondary_color: "#be185d",
      background_color: "#fdf2f8",
      text_color: "#831843",
      accent_color: "#f472b6",
      surface_color: "#ffffff",
      heading_color: "#701a3c",
      border_color: "#fbcfe8",
      font_family: "dmSans",
      heading_font: "playfair",
      font_size: "medium",
      layout_style: "grid",
      card_style: "modern",
      border_radius: "pill",
      card_shadow: "soft",
      button_style: "soft",
      button_radius: "pill",
      animation_style: "zoom",
      spacing: "spacious",
      header_style: "transparent",
      image_aspect_ratio: "portrait",
      primary_gradient: "linear-gradient(to right, #0f172a, #334155)",
      glass_effect: true,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "left",
      logo_frame: "rounded",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "featured-products", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
      { id: "testimonials", enabled: true, order: 3 },
      { id: "about-section", enabled: true, order: 4 },
      { id: "contact-cta", enabled: true, order: 5 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Glow from within",
        subtitle:
          "Premium skincare and beauty essentials curated for radiant skin.",
        cta_text: "Browse Collection",
        cta_link: "#item-list",
        text_align: "center",
      },
      "about-section": {
        title: "Our Story",
        text: "We believe everyone deserves to feel beautiful. Our curated collection brings the best skincare straight to your doorstep.",
      },
    },
  },

  // ── 5. Quick Bites (preserved ID) ──────────────────────────
  {
    id: "quick-bites",
    name: "Quick Bites",
    description: "Fast, bold & appetising — for food vendors & restaurants.",
    emoji: "🍔",
    category: "food",
    tags: ["food", "restaurant", "bold"],
    theme: {
      primary_color: "#dc2626",
      secondary_color: "#b91c1c",
      background_color: "#fffbeb",
      text_color: "#451a03",
      accent_color: "#f59e0b",
      surface_color: "#ffffff",
      heading_color: "#3b0a02",
      border_color: "#fde68a",
      font_family: "montserrat",
      heading_font: "montserrat",
      font_size: "large",
      layout_style: "list",
      card_style: "bold",
      border_radius: "rounded",
      card_shadow: "hard",
      button_style: "solid",
      button_radius: "rounded",
      animation_style: "bounce",
      spacing: "compact",
      header_style: "sticky",
      image_aspect_ratio: "landscape",
      primary_gradient: "linear-gradient(135deg, #dc2626, #ef4444)",
      glass_effect: false,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "left",
      logo_frame: "rounded",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "announcement-bar", enabled: true, order: 1 },
      { id: "featured-products", enabled: true, order: 2 },
      { id: "product-grid", enabled: true, order: 3 },
      { id: "trust-badges", enabled: true, order: 4 },
      { id: "contact-cta", enabled: true, order: 5 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Hungry? Order now",
        subtitle: "Delicious meals ready in minutes — straight to your door.",
        cta_text: "See Menu",
        cta_link: "#item-list",
        text_align: "left",
      },
      "featured-products": {
        title: "Most Popular",
        product_ids: [],
      },
      "announcement-bar": {
        text: "Free delivery for orders above ₦3,000 today!",
        bg_color: "#dc2626",
        text_color: "#ffffff",
      },
      "trust-badges": {
        badges: [
          { icon: "clock", label: "30min Delivery" },
          { icon: "fresh", label: "Fresh Daily" },
          { icon: "price", label: "Best Prices" },
          { icon: "chat", label: "Order via WhatsApp" },
        ],
      },
    },
  },

  // ── 6. Handmade & Craft (preserved ID) ─────────────────────
  {
    id: "handmade-craft",
    name: "Handmade & Craft",
    description:
      "Warm, earthy & artisanal — for makers, artisans and creatives.",
    emoji: "🧶",
    category: "artisan",
    tags: ["handmade", "craft", "artisan"],
    theme: {
      primary_color: "#92400e",
      secondary_color: "#78350f",
      background_color: "#fefce8",
      text_color: "#422006",
      accent_color: "#d97706",
      surface_color: "#fffef2",
      heading_color: "#351c05",
      border_color: "#fde68a",
      font_family: "inter",
      heading_font: "playfair",
      font_size: "medium",
      layout_style: "masonry",
      card_style: "classic",
      border_radius: "rounded",
      card_shadow: "soft",
      button_style: "outline",
      button_radius: "rounded",
      animation_style: "fade",
      spacing: "spacious",
      header_style: "static",
      image_aspect_ratio: "square",
      primary_gradient: null,
      glass_effect: false,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "center",
      logo_frame: "rounded",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "product-grid", enabled: true, order: 1 },
      { id: "about-section", enabled: true, order: 2 },
      { id: "testimonials", enabled: true, order: 3 },
      { id: "image-gallery", enabled: true, order: 4 },
      { id: "contact-cta", enabled: true, order: 5 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Made with love",
        subtitle: "Handcrafted pieces, each one unique — made just for you.",
        cta_text: "Discover",
        cta_link: "#item-list",
        text_align: "center",
      },
      "about-section": {
        title: "The maker\u0027s story",
        text: "Every piece in our store is handmade with care and attention to detail, bringing a personal touch to everything we create.",
      },
    },
  },

  // ── 7. Midnight Luxe (NEW) ─────────────────────────────────
  {
    id: "midnight-luxe",
    name: "Midnight Luxe",
    description:
      "Dark, sophisticated & premium — for brands that demand attention.",
    emoji: "🌙",
    category: "premium",
    tags: ["dark", "premium", "luxury"],
    theme: {
      primary_color: "#a78bfa",
      secondary_color: "#7c3aed",
      background_color: "#0f0f14",
      text_color: "#e2e0ea",
      accent_color: "#fbbf24",
      surface_color: "#1a1a24",
      heading_color: "#f5f3ff",
      border_color: "#2e2e3a",
      font_family: "inter",
      heading_font: "outfit",
      font_size: "medium",
      layout_style: "grid",
      card_style: "modern",
      border_radius: "rounded",
      card_shadow: "elevated",
      button_style: "glass",
      button_radius: "rounded",
      animation_style: "fade",
      spacing: "comfortable",
      header_style: "transparent",
      image_aspect_ratio: "portrait",
      primary_gradient: "linear-gradient(180deg, #1a1a24 0%, #0f0f14 100%)",
      glass_effect: true,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "center",
      logo_frame: "profile",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "featured-products", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
      { id: "testimonials", enabled: true, order: 3 },
      { id: "trust-badges", enabled: true, order: 4 },
      { id: "contact-cta", enabled: true, order: 5 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Elevate your style",
        subtitle:
          "Premium collections for those who appreciate the finer things.",
        cta_text: "Explore",
        cta_link: "#item-list",
        text_align: "center",
      },
      "trust-badges": {
        badges: [
          { icon: "diamond", label: "Premium Quality" },
          { icon: "shield", label: "Secure Payment" },
          { icon: "rocket", label: "Priority Shipping" },
          { icon: "crown", label: "VIP Support" },
        ],
      },
      testimonials: {
        quotes: [
          {
            name: "David K.",
            text: "The quality is unmatched. Absolutely premium experience.",
            rating: 5,
          },
          {
            name: "Kemi O.",
            text: "Sleek packaging and fast delivery. Love this brand!",
            rating: 5,
          },
        ],
      },
    },
  },

  // ── 8. Studio Clean (NEW) ──────────────────────────────────
  {
    id: "studio-clean",
    name: "Studio Clean",
    description:
      "Ultra-minimal whitespace design — let your products speak for themselves.",
    emoji: "◻️",
    category: "premium",
    tags: ["minimal", "clean", "modern"],
    theme: {
      primary_color: "#0a0a0a",
      secondary_color: "#262626",
      background_color: "#ffffff",
      text_color: "#404040",
      accent_color: "#0a0a0a",
      surface_color: "#fafafa",
      heading_color: "#0a0a0a",
      border_color: "#f0f0f0",
      font_family: "dmSans",
      heading_font: "dmSans",
      font_size: "medium",
      layout_style: "grid",
      card_style: "minimal",
      border_radius: "sharp",
      card_shadow: "none",
      button_style: "solid",
      button_radius: "sharp",
      animation_style: "fade",
      spacing: "spacious",
      header_style: "static",
      image_aspect_ratio: "portrait",
      primary_gradient: null,
      glass_effect: false,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "left",
      logo_frame: "none",
      icon_library: "lucide",
      icon_fill: "outline",
      icon_weight: "regular",
      cart_icon: "tote",
      user_icon: "face",
      share_icon: "dots",
      add_icon: "plus",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "product-grid", enabled: true, order: 1 },
      { id: "about-section", enabled: true, order: 2 },
      { id: "contact-cta", enabled: true, order: 3 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Less is more.",
        subtitle: "A carefully curated selection of products you'll love.",
        cta_text: "Shop",
        cta_link: "#item-list",
        text_align: "left",
      },
      "about-section": {
        title: "Our Philosophy",
        text: "Quality over quantity. Every product in our store is thoughtfully selected to meet the highest standards.",
      },
    },
  },

  // ── 9. Vogue Minimal (Fashion) ─────────────────────────────
  {
    id: "vogue-minimal",
    name: "Vogue Minimal",
    description:
      "High-end editorial fashion look with large imagery and refined typography.",
    emoji: "👠",
    category: "fashion",
    tags: ["fashion", "premium", "editorial"],
    theme: {
      primary_color: "#000000",
      secondary_color: "#111111",
      background_color: "#ffffff",
      text_color: "#1a1a1a",
      accent_color: "#997d51",
      surface_color: "#ffffff",
      heading_color: "#000000",
      border_color: "#e5e5e5",
      font_family: "dmSans",
      heading_font: "playfair",
      font_size: "medium",
      layout_style: "masonry",
      card_style: "minimal",
      border_radius: "sharp",
      card_shadow: "none",
      button_style: "solid",
      button_radius: "sharp",
      animation_style: "fade",
      spacing: "spacious",
      header_style: "transparent",
      image_aspect_ratio: "portrait",
      primary_gradient: null,
      glass_effect: false,
      layout_width: "full",
      show_mobile_checkout_bar: true,
      logo_position: "center",
      logo_frame: "none",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "product-grid", enabled: true, order: 1 },
      { id: "logo-cloud", enabled: true, order: 2 },
      { id: "contact-cta", enabled: true, order: 3 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "The Autumn Collection",
        subtitle: "Essential pieces for the modern wardrobe.",
        cta_text: "Shop Collection",
        cta_link: "#item-list",
        text_align: "center",
      },
    },
  },

  // ── 10. Artisan Dark (Artisan) ─────────────────────────────
  {
    id: "artisan-dark",
    name: "Artisan Dark",
    description:
      "Deep earthy tones with subtle glassmorphism for a sophisticated craft look.",
    emoji: "🏺",
    category: "artisan",
    tags: ["artisan", "dark", "mature"],
    theme: {
      primary_color: "#c2410c",
      secondary_color: "#9a3412",
      background_color: "#1c1917",
      text_color: "#e7e5e4",
      accent_color: "#f97316",
      surface_color: "#292524",
      heading_color: "#fafaf9",
      border_color: "#44403c",
      font_family: "poppins",
      heading_font: "playfair",
      font_size: "medium",
      layout_style: "grid",
      card_style: "modern",
      border_radius: "rounded",
      card_shadow: "soft",
      button_style: "glass",
      button_radius: "rounded",
      animation_style: "fade",
      spacing: "comfortable",
      header_style: "sticky",
      image_aspect_ratio: "square",
      primary_gradient: "linear-gradient(135deg, #78350f, #92400e)",
      glass_effect: true,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "left",
      logo_frame: "rounded",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "rich-text", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
      { id: "contact-cta", enabled: true, order: 3 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Crafted with Intent",
        subtitle: "Every object tells a story of heritage and skill.",
        cta_text: "View Objects",
        text_align: "left",
      },
      "rich-text": {
        title: "The Maker’s Philosophy",
        text: "We believe in the beauty of imperfection and the value of things that take time to create.",
        align: "center",
      },
    },
  },

  // ── 11. Street Vibe (Fashion) ──────────────────────────────
  {
    id: "street-vibe",
    name: "Street Vibe",
    description:
      "Bold, high-contrast streetwear aesthetic with loud typography.",
    emoji: "🛹",
    category: "fashion",
    tags: ["fashion", "streetwear", "bold"],
    theme: {
      primary_color: "#facc15",
      secondary_color: "#000000",
      background_color: "#000000",
      text_color: "#ffffff",
      accent_color: "#ef4444",
      surface_color: "#1a1a1a",
      heading_color: "#facc15",
      border_color: "#262626",
      font_family: "montserrat",
      heading_font: "spaceGrotesk",
      font_size: "large",
      layout_style: "grid",
      card_style: "bold",
      border_radius: "sharp",
      card_shadow: "hard",
      button_style: "solid",
      button_radius: "sharp",
      animation_style: "bounce",
      spacing: "compact",
      header_style: "sticky",
      image_aspect_ratio: "portrait",
      primary_gradient: "linear-gradient(45deg, #facc15, #fb923c)",
      glass_effect: false,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "center",
      logo_frame: "none",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "announcement-bar", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
      { id: "contact-cta", enabled: true, order: 3 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "STREET DROP 01",
        subtitle: "The wait is over. Limited edition arrivals.",
        cta_text: "COP NOW",
        text_align: "center",
      },
      "announcement-bar": {
        text: "FREE GLOBAL SHIPPING ON ALL DROPS",
        bg_color: "#facc15",
        text_color: "#000000",
      },
    },
  },

  // ── 12. Vintage Retro (Fashion) ────────────────────────────
  {
    id: "vintage-retro",
    name: "Vintage Retro",
    description:
      "Warm cream tones and classic serifs for thrift and vintage shops.",
    emoji: "📻",
    category: "fashion",
    tags: ["vintage", "retro", "thrift"],
    theme: {
      primary_color: "#7c2d12",
      secondary_color: "#431407",
      background_color: "#fdf8f1",
      text_color: "#44403c",
      accent_color: "#d97706",
      surface_color: "#fffcf7",
      heading_color: "#431407",
      border_color: "#e7e5e4",
      font_family: "playfair",
      heading_font: "playfair",
      font_size: "medium",
      layout_style: "masonry",
      card_style: "classic",
      border_radius: "rounded",
      card_shadow: "soft",
      button_style: "outline",
      button_radius: "rounded",
      animation_style: "fade",
      spacing: "comfortable",
      header_style: "static",
      image_aspect_ratio: "portrait",
      primary_gradient: null,
      glass_effect: false,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "left",
      logo_frame: "rounded",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "about-section", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
      { id: "contact-cta", enabled: true, order: 3 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Timeless Treasures",
        subtitle: "Ethically curated vintage pieces with a story.",
        cta_text: "Explore Archive",
      },
    },
  },

  // ── 13. Gourmet Bistro (Food) ──────────────────────────────
  {
    id: "gourmet-bistro",
    name: "Gourmet Bistro",
    description:
      "Elegant charcoal and gold aesthetic for fine dining and bakeries.",
    emoji: "🍴",
    category: "food",
    tags: ["food", "elegant", "dining"],
    theme: {
      primary_color: "#c5a059",
      secondary_color: "#1a1a1a",
      background_color: "#111111",
      text_color: "#d4d4d4",
      accent_color: "#c5a059",
      surface_color: "#1a1a1a",
      heading_color: "#ffffff",
      border_color: "#262626",
      font_family: "dmSans",
      heading_font: "playfair",
      font_size: "medium",
      layout_style: "list",
      card_style: "minimal",
      border_radius: "sharp",
      card_shadow: "none",
      button_style: "solid",
      button_radius: "sharp",
      animation_style: "fade",
      spacing: "spacious",
      header_style: "transparent",
      image_aspect_ratio: "landscape",
      primary_gradient: "linear-gradient(135deg, #1a1a1a, #262626)",
      glass_effect: true,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "center",
      logo_frame: "profile",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "rich-text", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
      { id: "contact-cta", enabled: true, order: 3 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "The Art of Taste",
        subtitle: "Experience culinary excellence delivered to your door.",
        cta_text: "View Menu",
      },
    },
  },

  // ── 14. Coffee Roasters (Food) ─────────────────────────────
  {
    id: "coffee-roasters",
    name: "Coffee Roasters",
    description:
      "Warm browns and craft paper tones for cafes and coffee shops.",
    emoji: "☕",
    category: "food",
    tags: ["coffee", "cafe", "warm"],
    theme: {
      primary_color: "#462312",
      secondary_color: "#341a0d",
      background_color: "#f7f3f0",
      text_color: "#462312",
      accent_color: "#c59b3f",
      surface_color: "#ffffff",
      heading_color: "#341a0d",
      border_color: "#e2ddd9",
      font_family: "inter",
      heading_font: "spaceGrotesk",
      font_size: "medium",
      layout_style: "grid",
      card_style: "classic",
      border_radius: "rounded",
      card_shadow: "soft",
      button_style: "solid",
      button_radius: "rounded",
      animation_style: "slide",
      spacing: "comfortable",
      header_style: "sticky",
      image_aspect_ratio: "square",
      primary_gradient: null,
      glass_effect: false,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "left",
      logo_frame: "rounded",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "logo-cloud", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
      { id: "testimonials", enabled: true, order: 3 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Roasted with Soul",
        subtitle: "Specialty beans sourced directly from independent growers.",
        cta_text: "Shop Beans",
      },
    },
  },

  // ── 15. Cyber Matrix (Tech) ────────────────────────────────
  {
    id: "cyber-matrix",
    name: "Cyber Matrix",
    description: "High-tech neon aesthetic for gaming and futuristic hardware.",
    emoji: "⌨️",
    category: "tech",
    tags: ["tech", "gaming", "dark"],
    theme: {
      primary_color: "#22c55e",
      secondary_color: "#15803d",
      background_color: "#020617",
      text_color: "#94a3b8",
      accent_color: "#3b82f6",
      surface_color: "#0f172a",
      heading_color: "#f8fafc",
      border_color: "#1e293b",
      font_family: "roboto",
      heading_font: "spaceGrotesk",
      font_size: "medium",
      layout_style: "grid",
      card_style: "bold",
      border_radius: "sharp",
      card_shadow: "none",
      button_style: "glass",
      button_radius: "sharp",
      animation_style: "zoom",
      spacing: "comfortable",
      header_style: "sticky",
      image_aspect_ratio: "landscape",
      primary_gradient: "linear-gradient(90deg, #15803d, #22c55e)",
      glass_effect: true,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "center",
      logo_frame: "rounded",
    },
    sections: [
      { id: "announcement-bar", enabled: true, order: 0 },
      { id: "hero-banner", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
      { id: "trust-badges", enabled: true, order: 3 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Beyond the Circuit",
        subtitle: "Cutting-edge hardware for the next generation of creators.",
        cta_text: "Upgrade Now",
      },
    },
  },

  // ── 16. Minimal SaaS (Tech) ────────────────────────────────
  {
    id: "minimal-saas",
    name: "Minimal SaaS",
    description: "Clean software-style aesthetic with soft shadows and blues.",
    emoji: "☁️",
    category: "tech",
    tags: ["tech", "clean", "modern"],
    theme: {
      primary_color: "#4f46e5",
      secondary_color: "#4338ca",
      background_color: "#f8fafc",
      text_color: "#475569",
      accent_color: "#0ea5e9",
      surface_color: "#ffffff",
      heading_color: "#0f172a",
      border_color: "#cbd5e1",
      font_family: "inter",
      heading_font: "outfit",
      font_size: "medium",
      layout_style: "grid",
      card_style: "modern",
      border_radius: "rounded",
      card_shadow: "elevated",
      button_style: "solid",
      button_radius: "rounded",
      animation_style: "slide",
      spacing: "comfortable",
      header_style: "sticky",
      image_aspect_ratio: "landscape",
      primary_gradient: "linear-gradient(135deg, #6366f1, #4f46e5)",
      glass_effect: false,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "left",
      logo_frame: "rounded",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "logo-cloud", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
      { id: "faqs", enabled: true, order: 3 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Simplify your workflow",
        subtitle: "Powerful tools designed for speed and reliability.",
        cta_text: "Get Started",
        text_align: "left",
      },
    },
  },

  // ── 17. Gaming Pulse (Tech) ────────────────────────────────
  {
    id: "gaming-pulse",
    name: "Gaming Pulse",
    description: "Dark mode with neon purple/pink RGB accents for gamers.",
    emoji: "🎮",
    category: "tech",
    tags: ["gaming", "dark", "neon"],
    theme: {
      primary_color: "#8b5cf6",
      secondary_color: "#6d28d9",
      background_color: "#080112",
      text_color: "#a5b4fc",
      accent_color: "#f472b6",
      surface_color: "#150a24",
      heading_color: "#ffffff",
      border_color: "#2e1065",
      font_family: "outfit",
      heading_font: "spaceGrotesk",
      font_size: "medium",
      layout_style: "grid",
      card_style: "bold",
      border_radius: "rounded",
      card_shadow: "elevated",
      button_style: "solid",
      button_radius: "rounded",
      animation_style: "zoom",
      spacing: "comfortable",
      header_style: "transparent",
      image_aspect_ratio: "landscape",
      primary_gradient: "linear-gradient(90deg, #8b5cf6, #ec4899)",
      glass_effect: true,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "center",
      logo_frame: "rounded",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "featured-products", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
      { id: "contact-cta", enabled: true, order: 3 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "UNLEASH THE POWER",
        subtitle: "Pro-grade gaming gear for competitive elite.",
        cta_text: "Level Up",
        image_url:
          "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=1200&h=800&fit=crop",
      },
    },
  },

  // ── 18. Serene Spa (Beauty) ────────────────────────────────
  {
    id: "serene-spa",
    name: "Serene Spa",
    description:
      "Soft sage greens and airy whitespace for wellness and relaxation.",
    emoji: "🌿",
    category: "beauty",
    tags: ["wellness", "minimal", "calm"],
    theme: {
      primary_color: "#606c38",
      secondary_color: "#283618",
      background_color: "#fefae0",
      text_color: "#283618",
      accent_color: "#dda15e",
      surface_color: "#ffffff",
      heading_color: "#283618",
      border_color: "#c9ada7",
      font_family: "dmSans",
      heading_font: "playfair",
      font_size: "medium",
      layout_style: "masonry",
      card_style: "minimal",
      border_radius: "pill",
      card_shadow: "none",
      button_style: "soft",
      button_radius: "pill",
      animation_style: "fade",
      spacing: "spacious",
      header_style: "static",
      image_aspect_ratio: "portrait",
      primary_gradient: null,
      glass_effect: false,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "center",
      logo_frame: "rounded",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "image-gallery", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
      { id: "about-section", enabled: true, order: 3 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Find Your Calm",
        subtitle: "Natural remedies for mind, body, and soul.",
        cta_text: "De-stress Now",
      },
    },
  },

  // ── 19. Makeup Studio (Beauty) ─────────────────────────────
  {
    id: "makeup-studio",
    name: "Makeup Studio",
    description:
      "Hot pinks and gloss effects for professional makeup and cosmetics.",
    emoji: "💄",
    category: "beauty",
    tags: ["makeup", "glamour", "pink"],
    theme: {
      primary_color: "#be123c",
      secondary_color: "#9f1239",
      background_color: "#fff1f2",
      text_color: "#881337",
      accent_color: "#fb7185",
      surface_color: "#ffffff",
      heading_color: "#4c0519",
      border_color: "#fecdd3",
      font_family: "montserrat",
      heading_font: "montserrat",
      font_size: "medium",
      layout_style: "grid",
      card_style: "modern",
      border_radius: "rounded",
      card_shadow: "soft",
      button_style: "solid",
      button_radius: "rounded",
      animation_style: "zoom",
      spacing: "comfortable",
      header_style: "sticky",
      image_aspect_ratio: "square",
      primary_gradient: "linear-gradient(135deg, #e11d48, #fb7185)",
      glass_effect: true,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "left",
      logo_frame: "profile",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "featured-products", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
      { id: "testimonials", enabled: true, order: 3 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Fearless Beauty",
        subtitle:
          "Unleash your inner artist with professional grade cosmetics.",
        cta_text: "Shop Palettes",
        text_align: "center",
      },
    },
  },

  // ── 20. Organic Roots (Beauty) ─────────────────────────────
  {
    id: "organic-roots",
    name: "Organic Roots",
    description:
      "Earthy greens and recycling-inspired textures for eco-brands.",
    emoji: "🎋",
    category: "beauty",
    tags: ["eco", "natural", "organic"],
    theme: {
      primary_color: "#166534",
      secondary_color: "#14532d",
      background_color: "#f0fdf4",
      text_color: "#14532d",
      accent_color: "#84cc16",
      surface_color: "#ffffff",
      heading_color: "#064e3b",
      border_color: "#dcfce7",
      font_family: "dmSans",
      heading_font: "dmSans",
      font_size: "medium",
      layout_style: "grid",
      card_style: "minimal",
      border_radius: "rounded",
      card_shadow: "none",
      button_style: "soft",
      button_radius: "rounded",
      animation_style: "fade",
      spacing: "comfortable",
      header_style: "static",
      image_aspect_ratio: "square",
      primary_gradient: null,
      glass_effect: false,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "left",
      logo_frame: "rounded",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "trust-badges", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
      { id: "rich-text", enabled: true, order: 3 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Skin Kind, Earth Kind",
        subtitle: "100% organic, plastic-free skincare essentials.",
        cta_text: "Shop Sustainable",
      },
    },
  },

  // ── 21. Clay Pottery (Artisan) ─────────────────────────────
  {
    id: "clay-pottery",
    name: "Clay Pottery",
    description: "Terracotta and slate tones for ceramicists and sculptors.",
    emoji: "🏺",
    category: "artisan",
    tags: ["artisan", "pottery", "ceramics"],
    theme: {
      primary_color: "#9a3412",
      secondary_color: "#7c2d12",
      background_color: "#fdf8f6",
      text_color: "#431407",
      accent_color: "#c2410c",
      surface_color: "#ffffff",
      heading_color: "#431407",
      border_color: "#f1f1ef",
      font_family: "inter",
      heading_font: "playfair",
      font_size: "medium",
      layout_style: "masonry",
      card_style: "modern",
      border_radius: "pill",
      card_shadow: "soft",
      button_style: "outline",
      button_radius: "pill",
      animation_style: "fade",
      spacing: "spacious",
      header_style: "sticky",
      image_aspect_ratio: "square",
      primary_gradient: null,
      glass_effect: false,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "center",
      logo_frame: "rounded",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "product-grid", enabled: true, order: 1 },
      { id: "image-gallery", enabled: true, order: 2 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Shaped by Hand",
        subtitle: "Functional art for your daily rituals.",
        cta_text: "View Ceramics",
      },
    },
  },

  // ── 22. Leather & Grain (Artisan) ──────────────────────────
  {
    id: "leather-grain",
    name: "Leather & Grain",
    description:
      "Rugged tan and dark wood tones for leathercraft and woodworkers.",
    emoji: "👞",
    category: "artisan",
    tags: ["leather", "wood", "rugged"],
    theme: {
      primary_color: "#451a03",
      secondary_color: "#78350f",
      background_color: "#fffbeb",
      text_color: "#451a03",
      accent_color: "#92400e",
      surface_color: "#fafaf9",
      heading_color: "#451a03",
      border_color: "#e7e5e4",
      font_family: "roboto",
      heading_font: "playfair",
      font_size: "medium",
      layout_style: "grid",
      card_style: "classic",
      border_radius: "rounded",
      card_shadow: "soft",
      button_style: "solid",
      button_radius: "rounded",
      animation_style: "slide",
      spacing: "comfortable",
      header_style: "static",
      image_aspect_ratio: "portrait",
      primary_gradient: null,
      glass_effect: false,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "left",
      logo_frame: "rounded",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "product-grid", enabled: true, order: 1 },
      { id: "about-section", enabled: true, order: 2 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "Built to Last",
        subtitle: "Generations of craftsmanship in every stitch.",
        cta_text: "Shop Gear",
        image_url:
          "https://images.unsplash.com/photo-1481277542470-605612bd2d61?w=1200&h=800&fit=crop",
      },
    },
  },

  // ── 23. Monochrome Pro (Premium) ───────────────────────────
  {
    id: "monochrome-pro",
    name: "Monochrome Pro",
    description: "Strict black and white aesthetic with extreme whitespace.",
    emoji: "🏁",
    category: "premium",
    tags: ["monochrome", "minimal", "ultra"],
    theme: {
      primary_color: "#000000",
      secondary_color: "#000000",
      background_color: "#ffffff",
      text_color: "#000000",
      accent_color: "#000000",
      surface_color: "#ffffff",
      heading_color: "#000000",
      border_color: "#000000",
      font_family: "inter",
      heading_font: "inter",
      font_size: "medium",
      layout_style: "grid",
      card_style: "minimal",
      border_radius: "sharp",
      card_shadow: "none",
      button_style: "solid",
      button_radius: "sharp",
      animation_style: "none",
      spacing: "spacious",
      header_style: "transparent",
      image_aspect_ratio: "portrait",
      primary_gradient: null,
      glass_effect: false,
      layout_width: "full",
      show_mobile_checkout_bar: true,
      logo_position: "center",
      logo_frame: "none",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "logo-cloud", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "FORM & FUNCTION",
        subtitle: "The essential collection.",
        cta_text: "PURCHASE",
        image_url:
          "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=1200&h=800&fit=crop",
      },
    },
  },

  // ── 24. Gold Reserve (Premium) ─────────────────────────────
  {
    id: "gold-reserve",
    name: "Gold Reserve",
    description: "Deep navy and gold with premium glassmorphism effects.",
    emoji: "🏆",
    category: "premium",
    tags: ["luxury", "gold", "glass"],
    theme: {
      primary_color: "#fbbf24",
      secondary_color: "#d97706",
      background_color: "#020617",
      text_color: "#cbd5e1",
      accent_color: "#fbbf24",
      surface_color: "#0f172a",
      heading_color: "#ffffff",
      border_color: "#1e293b",
      font_family: "outfit",
      heading_font: "playfair",
      font_size: "medium",
      layout_style: "masonry",
      card_style: "modern",
      border_radius: "rounded",
      card_shadow: "elevated",
      button_style: "glass",
      button_radius: "pill",
      animation_style: "zoom",
      spacing: "spacious",
      header_style: "transparent",
      image_aspect_ratio: "portrait",
      primary_gradient: "linear-gradient(135deg, #fbbf24, #d97706)",
      glass_effect: true,
      layout_width: "wide",
      show_mobile_checkout_bar: true,
      logo_position: "center",
      logo_frame: "profile",
    },
    sections: [
      { id: "hero-banner", enabled: true, order: 0 },
      { id: "featured-products", enabled: true, order: 1 },
      { id: "product-grid", enabled: true, order: 2 },
      { id: "trust-badges", enabled: true, order: 3 },
    ],
    sectionContent: {
      ...DEFAULT_SECTION_CONTENT,
      "hero-banner": {
        title: "The Gold Standard",
        subtitle: "Uncompromising luxury for the discerning few.",
        cta_text: "Membership Access",
        image_url:
          "https://images.unsplash.com/photo-1618022325802-7e5e732d97a1?w=1200&h=800&fit=crop",
      },
    },
  },
];

// Helper to get a template by ID
export function getTemplateById(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

// Helper to get default template
export function getDefaultTemplate(): Template {
  return TEMPLATES[0]; // fresh-market
}

// All default sections (for creating new themes)
export function getDefaultSections(): TemplateSection[] {
  return [...DEFAULT_SECTIONS];
}

export function getDefaultSectionContent(): TemplateSectionContent {
  return JSON.parse(JSON.stringify(DEFAULT_SECTION_CONTENT));
}
